### PR TITLE
fix: download minify.exe

### LINKED ISSUE #27: AppData/Local/Temp/minify/minify.exe" because file does not exist.
Hi,

I installed your package in my Symfony 7.1 project using the command `composer require sensiolabs/minify-bundle`. I accepted the recipe.

Then i ran `php bin/console asset-map:compile` And I got the following error : 

```
C:\wamp64\www\retrocalage-symfo>php bin/console asset-map:compile

 ! [NOTE] Downloading Sass binary from https://github.com/sass/dart-sass/releases/download/1.69.7/dart-sass-1.69.7-windows-x64.zip

 4002605/4002605 [============================] 100%
 ! [NOTE] Executing Sass (pass -v to see more details).                                                                 

 // Compiling and writing asset files to public

19:55:44 CRITICAL  [console] Error thrown while running command "asset-map:compile". Message: "Failed to copy "C:/Users/antoi/AppData/Local/Temp/minify/minify.exe" because file does not exist." ["exception" => Symfony\Component\Filesystem\Exception\FileNotFoundException { …},"command" => "asset-map:compile","message" => "Failed to copy "C:/Users/antoi/AppData/Local/Temp/minify/minify.exe" because file does not exist."]

In Filesystem.php line 41:
                                                                                                     
  Failed to copy "C:/Users/antoi/AppData/Local/Temp/minify/minify.exe" because file does not exist.  
                                                                                                     

asset-map:compile
```

I then tried to run `php bin/console minify:install` but still the same output. I am missing something?

Thanks,
A.

### PR DESCRIPTION
**Pull request by smnandre**
(missed a `.exe` here..)

May fix #27

### CODE REVIEW

**Comment by seb-jean** [comment]
It's ok but I have another error when I do `php bin/console asset-map:compile`.

**Comment by smnandre** [comment]
Thank you @seb-jean ! Is it the same if you try to compile a single file with `minify:asset` ?   

(`minify:asset --help` for usage example) 

😮‍💨 Not easy to debug...  Without windows available i may drop its support for now and release the 1.0 without.. I hope not to, but it's not easy to debug / understand what's happenin :|

**Comment by seb-jean** [comment]
With `minify:asset`, I have

```
In Minify.php line 42:

  [Sensiolabs\MinifyBundle\Exception\RuntimeException]
  Minify error 1: "General error".


Exception trace:
  at C:\wamp64\www\demo\vendor\sensiolabs\minify-bundle\src\Minify.php:42
 Sensiolabs\MinifyBundle\Minify->minify() at C:\wamp64\www\demo\vendor\sensiolabs\minify-bundle\src\Minifier\TraceableMinifier.php:39
 Sensiolabs\MinifyBundle\Minifier\TraceableMinifier->minify() at C:\wamp64\www\demo\vendor\sensiolabs\minify-bundle\src\Command\MinifyAssetCommand.php:109
 Sensiolabs\MinifyBundle\Command\MinifyAssetCommand->execute() at C:\wamp64\www\demo\vendor\symfony\console\Command\Command.php:279
 Symfony\Component\Console\Command\Command->run() at C:\wamp64\www\demo\vendor\symfony\console\Application.php:1094
 Symfony\Component\Console\Application->doRunCommand() at C:\wamp64\www\demo\vendor\symfony\framework-bundle\Console\Application.php:123
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at C:\wamp64\www\demo\vendor\symfony\console\Application.php:342
 Symfony\Component\Console\Application->doRun() at C:\wamp64\www\demo\vendor\symfony\framework-bundle\Console\Application.php:77
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at C:\wamp64\www\demo\vendor\symfony\console\Application.php:193
 Symfony\Component\Console\Application->run() at C:\wamp64\www\demo\vendor\symfony\runtime\Runner\Symfony\ConsoleApplicationRunner.php:49
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at C:\wamp64\www\demo\vendor\autoload_runtime.php:29
 require_once() at C:\wamp64\www\demo\bin\console:15

minify:asset [-t|--type TYPE] [--] <input> [<output>]
```

**Comment by smnandre** [comment]
Well ... i'll have a deeper look after a little break :|

**Comment by seb-jean** [comment]
No problem!

**Comment by smnandre** [comment]
Sorry @seb-jean  last time i bother you with this... 

I made another attempt (just pushed on this branch) and i hope this is the good one 🤞 

Could you by chance try with this PR again....  ?

If this still does not work, you'd be a giant help if you could 
- check the minify var directory (`ls -la var` on unix systems, not sure on windows)
- list the file and see its authorisations (`ls -la var/minify`)
- see if you can run it by checking the version (`./var/minify/minify.exe --version -v`)
- run the binary file yourself ? 

Thank you 🙏

**Comment by seb-jean** [comment]
Oh no, you're not bothering me!

Yes, it's good 👌! Well done @smnandre !

**Comment by smnandre** [comment]
Thank you very very much for your help! 🙇

**Pull request merged**
